# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
include:
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/workflow.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/static.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/docker.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/gitlab_settings/.gitlab-ci.yml
    inputs:
      ocudu_path: $[[ inputs.ocudu_path ]]
      ocudu_ref: $[[ inputs.ocudu_ref ]]

variables:
  OCUDU_REGISTRY_URI: ${CI_TEMPLATE_REGISTRY_HOST}/$[[ inputs.ocudu_path ]]

stages:
  - ci
  - test
  - build
  - publish

headers:
  stage: ci
  extends: .headers

o1 integration tests downstream:
  stage: test
  inherit:
    variables: false
  rules:
    # here we can not use the predefined variables ON_MR and ON_MR_TRAIN because
    # inheriting them in the parent pipeline will also pass them to the child pipeline
    # thus triggering the whole child pipeline instead of just o1 integration tests job
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE == "merged_result"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    O1_TESTS_UPSTREAM_COMPONENT: ocudu_o1_adapter
    O1_TESTS_UPSTREAM_PROJECT_PATH: $CI_PROJECT_PATH
    O1_TESTS_UPSTREAM_SHA: $CI_COMMIT_SHA
  trigger:
    project: ocudu/ocudu_elements/ocudu_oran_apps/ocudu_o1_tests
    branch: main
    strategy: mirror

################################################################################
# Publish Docker images
################################################################################

.publish:
  stage: publish
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Nightly/
  retry: 2
  interruptible: false

o1_adapter image:
  extends:
    - .docker-builder
    - .publish
  variables: &o1-adapter-image-variables
    # Docker
    REGISTRY_URI: ${CI_REGISTRY_IMAGE}
    CONTEXT: ${CI_PROJECT_DIR}
    MODE: publish
  tags:
    - saas-linux-medium-${PLATFORM}
  before_script:
    # Set variables
    - |
      export NAME="o1_adapter_nightly_${SUFFIX}"
      export VERSION="$(git show -s --date=format:%Y%m%d --format=%cd ${CI_COMMIT_SHA})_${CI_COMMIT_SHORT_SHA}"
      echo "CI_SHARED_O1_ADAPTER_IMAGE_VERSION=${VERSION}" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env
  parallel: &matrix-o1-adapter-image-variants
    matrix:
      # AMD
      - SUFFIX: amd64
        MARCH: x86-64-v3
        TAG: amd64
        PLATFORM: amd64
      # ARM
      - SUFFIX: arm64
        MARCH: armv8.2-a+crypto+fp16+dotprod
        TAG: arm64
        PLATFORM: arm64
  needs: []

o1_adapter image update latest:
  extends:
    - .docker manifest
    - .publish
  variables:
    <<: *o1-adapter-image-variables

  script:
    - |
      export NAME="o1_adapter_nightly_${SUFFIX}"
      export VERSION="${CI_SHARED_O1_ADAPTER_IMAGE_VERSION}"
      docker manifest create ${REGISTRY_URI}/${NAME}:latest --amend ${REGISTRY_URI}/${NAME}:${VERSION}
      docker manifest push ${REGISTRY_URI}/${NAME}:latest
      echo "Image ${RETINA_REGISTRY_URI}/${NAME}:latest pushed"
  parallel: *matrix-o1-adapter-image-variants
  needs:
    - job: o1_adapter image
      artifacts: true
